### ISSUE TITLE
lincese is needed

### ISSUE THREAD

**Issue by nico202** [unsuitable001/pip-arm-wheel#1]
If you distribute the binaries you need to distribute the licenses too. You cannot just say "It's not mine so it doesn't matter".

**Comment by unsuitable001** [comment]
Will hyperlink to the original module's repo on my readme file work? Or, have to link the LICENSE file of them too? Or, have to add the LICENSE.md files to my repo too?

Thanks for your concern.

**Comment by nico202** [comment]
gevent & greenlet are under MIT, the license says:

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

While lxml (BSD):
```
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
```

I'm not 100% sure but I'd state in the readme the license each component has, linking to the license text.

**Comment by unsuitable001** [comment]
Oh. Thanks buddy. You can do a PR. Or, I'll do it ASAP.
